name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun build
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "dist/"
      - uses: actions/deploy-pages@v4.0.5
